-- AlterTable
ALTER TABLE `User` ADD COLUMN `bio` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `dateJoined` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `displayName` VARCHAR(191) NULL,
    ADD COLUMN `isAdmin` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isVerified` BOOLEAN NOT NULL DEFAULT false;
